# Generated by Django 5.0.4 on 2024-06-01 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="movie",
        ),
    ]
