# Generated by Django 5.0.4 on 2024-06-01 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event_reservation", "0002_remove_event_reservation_qr_code"),
        ("event_showtime", "0002_alter_showtime_events_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event_reservation",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="event_showtime.showtime_events",
            ),
        ),
    ]
