# Generated by Django 5.0.4 on 2024-06-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merch", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="merch_type",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
