# Generated by Django 4.1.3 on 2024-03-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="Cast",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="movie",
            name="Poster",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="Release_Date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
