# Generated by Django 4.1.3 on 2024-03-17 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_alter_movie_cast_alter_movie_poster_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie",
            old_name="Title",
            new_name="title",
        ),
    ]
