# Generated by Django 4.1.3 on 2024-03-17 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0004_rename_director_movie_production_companies"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie",
            old_name="production_companies",
            new_name="ProductionCompanies",
        ),
    ]
