# Generated by Django 4.1.3 on 2024-03-17 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0006_alter_movie_cast"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie",
            old_name="Cast",
            new_name="Movie_Cast",
        ),
    ]
