# Generated by Django 4.1.3 on 2024-03-17 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0007_rename_cast_movie_movie_cast"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="Movie_Cast",
            field=models.CharField(default=list, max_length=1000),
        ),
    ]
