# Generated by Django 4.1.3 on 2024-03-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0008_alter_movie_movie_cast"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
