# Generated by Django 5.0.4 on 2024-05-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0009_alter_movie_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
