# Generated by Django 5.0.4 on 2024-05-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0010_alter_movie_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="Category",
            field=models.CharField(max_length=100000),
        ),
        migrations.AlterField(
            model_name="movie",
            name="Duration",
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name="movie",
            name="Genre",
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name="movie",
            name="Language",
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name="movie",
            name="Movie_Cast",
            field=models.CharField(default=list, max_length=10000),
        ),
        migrations.AlterField(
            model_name="movie",
            name="ProductionCompanies",
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name="movie",
            name="country",
            field=models.CharField(max_length=100000),
        ),
        migrations.AlterField(
            model_name="movie",
            name="title",
            field=models.CharField(max_length=10000),
        ),
    ]
