# Generated by Django 5.0.4 on 2024-06-01 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="countries",
        ),
        migrations.RemoveField(
            model_name="event",
            name="sponsors",
        ),
        migrations.AddField(
            model_name="event",
            name="guests",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="event",
            name="private",
            field=models.BooleanField(default=False),
        ),
    ]
