# Generated by Django 4.1.3 on 2024-02-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinephile", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=500),
        ),
    ]
