# Generated by Django 4.1.3 on 2024-02-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinephile", "0002_alter_user_password"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="Email",
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
