# Generated by Django 4.1.3 on 2024-02-21 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinephile", "0004_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
