# Generated by Django 5.0.4 on 2024-05-03 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinephile", "0005_alter_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="pin",
            field=models.IntegerField(default=0),
        ),
    ]
