# Generated by Django 5.0.4 on 2024-05-05 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cinephile", "0006_user_pin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="pin",
        ),
    ]
