# Generated by Django 5.0.4 on 2024-05-31 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinephile", "0007_remove_user_pin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="Fidelity_Points",
            field=models.FloatField(default=0),
        ),
    ]
