# Generated by Django 5.0.4 on 2024-06-01 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movie_reservation", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie_reservation",
            name="qr_code",
        ),
    ]
