# Generated by Django 5.0.4 on 2024-06-01 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event_showtime", "0001_initial"),
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="showtime_events",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="events.event"
            ),
        ),
    ]
